name: Deploy VitePress to My Server

on:
  push:
    branches: [main]
  workflow_dispatch: # 👈 这一行就是手动触发开关

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: pre build
        run: pnpm stub

      - name: Build VitePress
        run: pnpm docs:build

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@v5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVERSSHKEY }}
          REMOTE_HOST: ${{ secrets.SERVERHOST }}
          REMOTE_PORT: ${{ secrets.SERVERPORT }}
          REMOTE_USER: ${{ secrets.SERVERUSER }}
          SOURCE: "docs/.vitepress/dist/"
          TARGET: "/srv/vitepress-site/current" # 👈 记得改成你服务器真实路径
          ARGS: "-avz --delete"
